### PR TITLE
Making edits to the notebooks in view of NCAS summer school

### PR DESCRIPTION
**Pull request by dorchard**
Mostly extra comments for documentation and guidance.

(Original plan was to do more such tweaks for the other notebooks, but this wasn't done in the end).
- [x] 01_penguin_classification.ipynb
- [x] consistent between exercises and worked solutions

### CODE REVIEW

**Review by jatkinson1000 — COMMENTED** [review]
I am doing some winter cleaning, so do you want to finish off and merge this PR, or shall I close it?

If merging please could you make sure that any changes to the exercises are also reflected in the worked solutions notebooks as well please.

**Comment by dorchard** [comment]
Okay done. Should I target this to `colab` not `main`?

**Comment by jatkinson1000** [comment]
Thanks.
Perhaps not as many changes as we were hoping, but at least what is here is now consistent, thank you.
I'll merge now into main as a squash, and then merge from main to the colab branch to keep it up to date.

**Review by jatkinson1000 — APPROVED** [review]
All looks good, thanks for bringing this to a finished state. Will squash and merge, then bring to Colab branch. 🎄

**Comment by dorchard** [comment]
Yes sorry I didn't do more on this. I thought at least worth just making my very minor tweaks consistent!

**Comment by jatkinson1000** [comment]
Not your fault - we are all overly busy so consolidating what is here so we can clean is appreciated :)

**Pull request merged**
