### PR TITLE
Cnn classification sols

### PR DESCRIPTION
**Pull request by jatkinson1000**
Worked solutions for the MNIST CNN classification exercise.

### CODE REVIEW

**Review by jatkinson1000 — COMMENTED** [review]
Clearly much faster on GPU.

Can you check over the spaces that were left for answers and add anything I've missed?
Not sure if there were any other transformations that were useful to include, or what to set the parameters in `jitter` to.

**Comment by jdenholm** [comment]
> Clearly much faster on GPU.
> 
> Can you check over the spaces that were left for answers and add anything I've missed? Not sure if there were any other transformations that were useful to include, or what to set the parameters in `jitter` to.

I had a go with smaller CNNs and it was still quite slow. On my hope PC, the time per epoch using the CPU was only a couple of minutes of so using mobile net, and not much different with smaller models.

I will look over the spaces shortly.

**Comment by jatkinson1000** [comment]
Haven't yet checked on intel, but I found that installing the nightly build allows access to the TPU capabilities using a similar approach to cuda:

```
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")
```

https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/
https://developer.apple.com/metal/pytorch/

Might need to add this to the docs (will open issue) and to the code (will open PR).

**Comment by jatkinson1000** [comment]
Just running this on my frame.work with an i5

About 3.5 min per epoch (plus a lot of fan) so seems reasonable.

My guess is that no-one has bothered implementing pytorch properly for apple silicon cpu architecture on the assumption that people will use the tpu backend.
Shocked it's as slow as it is though!

Anyway, happy to sign off on the timing issues as resolved.

@jdenholm did you have any comments on the addition of the `mps.is_available()`?
Requires torch >= 2.0 I think which I have opened a PR for to the main branch.

**Pull request merged**
